// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
export type ChainId =
  | "ETH"
  | "SOL"
  | "BASE"
  | "BNB"
  | "ARB"
  | "OP"
  | "MATIC"
  | "AVAX"
  | "HYPE"
  | "WETH"

export type DexId =
  | "uniswap"
  | "pancakeswap"
  | "aerodrome"
  | "orca"
  | "raydium"
  | "curve"
  | "meteora"
  | "hyperliquid"
  | "dydx"
  | "jupiter"
  | "pumpswap"
  | "pumpfun"
  | "1inch"

export type IconId = ChainId | DexId

export const CHAIN_IDS: readonly ChainId[] = ["ETH", "SOL", "BASE", "BNB", "ARB", "OP", "MATIC", "AVAX", "HYPE", "WETH"]
export const DEX_IDS: readonly DexId[] = ["uniswap", "pancakeswap", "aerodrome", "orca", "raydium", "curve", "meteora", "hyperliquid", "dydx", "jupiter", "pumpswap", "pumpfun", "1inch"]
