// AUTO-GENERATED by scripts/build-icons.mjs — do not edit by hand.
/* eslint-disable */
import { eth, sol, base, bnb, arb, op, matic, avax, hype, weth, uniswap, pancakeswap, aerodrome, orca, raydium, curve, meteora, hyperliquid, dydx, jupiter, pumpswap, pumpfun, oneInch } from '@crypto-elements/core'
import { createIcon } from './create-icon'

export const EthIcon = /*#__PURE__*/ createIcon(eth)
export const SolIcon = /*#__PURE__*/ createIcon(sol)
export const BaseIcon = /*#__PURE__*/ createIcon(base)
export const BnbIcon = /*#__PURE__*/ createIcon(bnb)
export const ArbIcon = /*#__PURE__*/ createIcon(arb)
export const OpIcon = /*#__PURE__*/ createIcon(op)
export const MaticIcon = /*#__PURE__*/ createIcon(matic)
export const AvaxIcon = /*#__PURE__*/ createIcon(avax)
export const HypeIcon = /*#__PURE__*/ createIcon(hype)
export const WethIcon = /*#__PURE__*/ createIcon(weth)
export const UniswapIcon = /*#__PURE__*/ createIcon(uniswap)
export const PancakeswapIcon = /*#__PURE__*/ createIcon(pancakeswap)
export const AerodromeIcon = /*#__PURE__*/ createIcon(aerodrome)
export const OrcaIcon = /*#__PURE__*/ createIcon(orca)
export const RaydiumIcon = /*#__PURE__*/ createIcon(raydium)
export const CurveIcon = /*#__PURE__*/ createIcon(curve)
export const MeteoraIcon = /*#__PURE__*/ createIcon(meteora)
export const HyperliquidIcon = /*#__PURE__*/ createIcon(hyperliquid)
export const DydxIcon = /*#__PURE__*/ createIcon(dydx)
export const JupiterIcon = /*#__PURE__*/ createIcon(jupiter)
export const PumpswapIcon = /*#__PURE__*/ createIcon(pumpswap)
export const PumpfunIcon = /*#__PURE__*/ createIcon(pumpfun)
export const OneinchIcon = /*#__PURE__*/ createIcon(oneInch)
